version: "3.9"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: ideaboard-db
    environment:
      POSTGRES_DB: ideaboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ideaboard"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideaboard-backend
    environment:
      PORT: 4000
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ideaboard
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: ideaboard-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
